[supabase]
url = "https://bidvgtspaijadkddvbxv.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZHZndHNwYWlqYWRrZGR2Ynh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTA0MjMsImV4cCI6MjA2MTU2NjQyM30.1C4UCQe_1uSXvv0Y1ALJVzkQvejoy__xpHygc2NmeCY"
bucket = "cv-uploads"
